import {library} from '@fortawesome/fontawesome-svg-core';
import {
  faCcPaypal,
  faCcVisa,
  faCcMastercard,
  faCcDiscover,
  faCcApplePay,
  faCcAmex,
  faApplePay,
  faGooglePay,
  faCcJcb,
  faCcDinersClub,
} from '@fortawesome/free-brands-svg-icons';

import {
  // FILES / DOCS / ETC.
  faFolder as faFolderSolid,
  faFolderOpen as faFolderOpenSolid,
  faFile as faFileSolid,
  faFileAlt as faFileAltSolid,
  faClipboardList as faClipboardListSolid,
  faFilePdf as faFilePdfSolid,
  faFileInvoice as faFileInvoiceSolid,
  faNewspaper as faNewspaperSolid,
  faIdCard as faIdCardSolid,
  faClone as faCloneSolid,
  faPrint as faPrintSolid,
  faLock as faLockSolid,
  faLockAlt as faLockAltSolid,
  faBriefcase as faBriefcaseSolid,
  faWindowMaximize as faWindowMaximizeSolid,
  faColumns as faColumnsSolid,
  faSquareFull as faSquareFullSolid,
  faUpload as faUploadSolid,
  faDatabase as faDatabaseSolid,

  // TIME
  faCalendarAlt as faCalendarAltSolid,
  faCalendarDay as faCalendarDaySolid,
  faCalendarCheck as faCalendarCheckSolid,
  faCalendarTimes as faCalendarTimesSolid,
  faClock as faClockSolid,
  faAlarmClock as faAlarmClockSolid,
  faHistory as faHistorySolid,
  faRedo as faRedoSolid,
  faSync as faSyncSolid,

  // CONTROLS / SETTINGS / HEARTS ...
  faFilter as faFilterSolid,
  faListOl as faListOlSolid,
  faList as faListSolid,
  faBars as faBarsSolid,
  faEllipsisH as faEllipsisHSolid,
  faEllipsisV as faEllipsisVSolid,
  faEdit as faEditSolid,
  faExternalLink as faExternalLinkSolid,
  faTrashAlt as faTrashAltSolid,
  faSave as faSaveSolid,
  faCog as faCogSolid,
  faTachometerAlt as faTachometerAltSolid,
  faPlusCircle as faPlusCircleSolid,
  faMinusCircle as faMinusCircleSolid,
  faStar as faStarSolid,
  faStars as faStarsSolid,
  faHeart as faHeartSolid,
  faShip as faShipSolid,
  faCar as faCardSolid,

  // CHECKS / INFO / WARNING
  faCheck as faCheckSolid,
  faCheckDouble as faCheckDoubleSolid,
  faShieldCheck as faShieldCheckSolid,
  faCheckCircle as faCheckCircleSolid,
  faClipboardCheck as faClipboardCheckSolid,
  faClipboardListCheck as faClipboardListCheckSolid,
  faSearch as faSearchSolid,
  faTimes as faTimesSolid,
  faCircle as faCircleSolid,
  faQuestionCircle as faQuestionCircleSolid,
  faInfoCircle as faInfoCircleSolid,
  faInfo as faInfoSolid,
  faExclamationCircle as faExclamationCircleSolid,

  // AROWS
  faChevronUp as faChevronUpSolid,
  faChevronDown as faChevronDownSolid,
  faChevronRight as faChevronRightSolid,
  faChevronLeft as faChevronLeftSolid,
  faArrowRight as faArrowRightSolid,
  faArrowLeft as faArrowLeftSolid,
  faArrowCircleUp as faArrowCircleUpSolid,
  faSignOut as faSignOutSolid,
  faSignIn as faSignInSolid,
  faSortAlt as faSortAltSolid,
  faExchangeAlt as faExchangeAltSolid,
  faRandom as faRandomSolid,
  faCaretDown as faCaretDownSolid,
  faSignOutAlt as faSignOutAltSolid,
  faLevelUp as faLevelUpSolid,
  faArrowToBottom as faArrowToBottomSolid,

  // USER
  faUser as faUserSolid,
  faUserCircle as faUserCircleSolid,
  faUsers as faUsersSolid,
  faUserFriends as faUserFriendsSolid,
  faChild as faChildSolid,
  faWheelchair as faWheelchairSolid,
  faSwimmer as faSwimmerSolid,

  // MAPS & LOCATION
  faMap as faMapSolid,
  faMapMarkerAlt as faMapMarkerAltSolid,
  faThumbtack as faThumbtackSolid,
  faMapMarkedAlt as faMapMarkedAltSolid,
  faLocationArrow as faLocationArrowSolid,
  faGlobeAmericas as faGlobeAmericasSolid,
  faLocation as faLocationSolid,
  faAnchor as faAnchorSolid,

  // MONEY
  faCoins as faCoinsSolid,
  faUsdCircle as faUsdCircleSolid,
  faHandHoldingUsd as faHandHoldingUsdSolid,
  faDollarSign as faDollarSignSolid,
  faMoneyBillWave as faMoneyBillWaveSolid,
  faPiggyBank as faPiggyBankSolid,
  faMoneyCheckAlt as faMoneyCheckAltSolid,
  faMoneyCheck as faMoneyCheckSolid,

  // CHARTS/ MEDIA / DEVICES
  faChartLine as faChartLineSolid,
  faChartBar as faChartBarSolid,
  faSignal as faSignalSolid,
  faWaveformPath as faWaveformPathSolid,
  faWifi as faWifiSolid,
  faWifiSlash as faWifiSlashSolid,
  faWrench as faWrenchSolid,
  faCamera as faCameraSolid,
  faImage as faImageSolid,
  faImages as faImagesSolid,
  faFilm as faFilmSolid,
  faMobileAlt as faMobileAltSolid,
  faPlay as faPlaySolid,
  faPause as faPauseSolid,

  // COMMUNICATION
  faComment as faCommentSolid,
  faComments as faCommentsSolid,
  faCommentCheck as faCommentCheckSolid,
  faSms as faSmsSolid,
  faEnvelope as faEnvelopeSolid,
  faPaperPlane as faPaperPlaneSolid,
  faLightbulbOn as faLightbulbOnSolid,
  faBell as faBellSolid,
  faBells as faBellsSolid,
  faMegaphone as faMegaphoneSolid,
  faPhoneAlt as faPhoneAltSolid,
  faShareAlt as faShareAltSolid,
  faInboxIn as faInboxInSolid,
  faInboxOut as faInboxOutSolid,

  // WEATHER
  faBolt as faBoltSolid,
  faMoon as faMoonSolid,
  faClouds as faCloudsSolid,
  faWind as faWindSolid,
  faWater as faWaterSolid,
  faWaterRise as faWaterRiseSolid,
  faWaterLower as faWaterLowerSolid,
  faFire as faFireSolid,
  faHurricane as faHurricaneSolid,
  faRaindrops as faRaindropsSolid,
  faUmbrella as faUmbrellaSolid,
  faSnowflake as faSnowflakeSolid,
  faTemperatureLow as faTemperatureLowSolid,
  faTemperatureHigh as faTemperatureHighSolid,
  faUmbrellaBeach as faUmbrellaBeachSolid,

  // OTHER
  faBurgerSoda as faBurgerSodaSolid,
  faGlassCitrus as faGlassCitrusSolid,
  faUtensils as faUtensilsSolid,
  faFish as faFishSolid,
  faTrophy as faTrophySolid,
  faTrophyAlt as faTrophyAltSolid,
  faMedal as faMedalSolid,
  faMagic as faMagicSolid,
  faVirus as faVirusSolid,
  faEyeSlash as faEyeSlashSolid,
  faEye as faEyeSolid,
  faThumbsDown as faThumbsDownSolid,
  faThumbsUp as faThumbsUpSolid,
  faHandPointRight as faHandPointRightSolid,
  faHandPointLeft as faHandPointLeftSolid,
  faBan as faBanSolid,
  faCreditCard as faCreditCardSolid,
  faSort as faSortSolid,
  faAngleRight as faAngleRightSolid,
  faAngleDown as faAngleDownSolid,
  faMoneyBillAlt as faMoneyBillAltSolid,
  faUniversity as faUniversitySolid,
  faUndo as faUndoSolid,
  faDownload as faDownloadSolid,
} from '@fortawesome/pro-solid-svg-icons';

import {
  // FILES / DOCS / ETC.
  faFolder,
  faFolderOpen,
  faFile,
  faFileAlt,
  faClipboardList,
  faFilePdf,
  faFileInvoice,
  faNewspaper,
  faIdCard,
  faClone,
  faPrint,
  faLock,
  faBriefcase,
  faWindowMaximize,
  faColumns,
  faSquareFull,
  faUpload,
  faDatabase,
  faArchive,

  // TIME
  faCalendarAlt,
  faCalendarDay,
  faCalendarCheck,
  faCalendarTimes,
  faClock,
  faAlarmClock,
  faHistory,
  faRedo,
  faSync,

  // CONTROLS / SETTINGS / HEARTS ...
  faFilter,
  faListOl,
  faList,
  faBars,
  faEllipsisH,
  faEllipsisV,
  faEdit,
  faExternalLink,
  faTrashAlt,
  faSave,
  faCog,
  faTachometerAlt,
  faPlusCircle,
  faMinusCircle,
  faStar,
  faStars,
  faHeart,
  faShip,
  faCar,

  // CHECKS / INFO / WARNING
  faCheck,
  faCheckDouble,
  faShieldCheck,
  faCheckCircle,
  faClipboardCheck,
  faClipboardListCheck,
  faSearch,
  faTimes,
  faCircle,
  faQuestionCircle,
  faInfoCircle,
  faInfo,
  faExclamationCircle,

  // AROWS
  faLongArrowAltUp,
  faChevronUp,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faArrowRight,
  faArrowLeft,
  faSignOut,
  faSignIn,
  faSortAlt,
  faExchangeAlt,
  faRandom,
  faCaretDown,
  faSignOutAlt,
  faLevelUp,
  faArrowToBottom,

  // USER
  faUser,
  faUserCircle,
  faUsers,
  faUserFriends,
  faChild,
  faWheelchair,
  faSwimmer,

  // MAPS & LOCATION
  faMap,
  faMapMarkerAlt,
  faThumbtack,
  faMapMarkedAlt,
  faLocationArrow,
  faGlobeAmericas,
  faLocation,
  faAnchor,

  // MONEY
  faCoins,
  faUsdCircle,
  faHandHoldingUsd,
  faDollarSign,
  faMoneyBillWave,
  faPiggyBank,
  faMoneyCheckAlt,
  faMoneyCheck,

  // CHARTS/ MEDIA / DEVICES
  faChartLine,
  faChartBar,
  faSignal,
  faWaveformPath,
  faWifi,
  faWifiSlash,
  faWrench,
  faCamera,
  faImage,
  faImages,
  faFilm,
  faMobileAlt,
  faPlay,
  faPause,
  faHeadset,

  // COMMUNICATION
  faComment,
  faComments,
  faCommentCheck,
  faSms,
  faEnvelope,
  faPaperPlane,
  faLightbulbOn,
  faBell,
  faBells,
  faMegaphone,
  faPhoneAlt,
  faShareAlt,
  faInboxIn,
  faInboxOut,

  // WEATHER
  faBolt,
  faMoon,
  faClouds,
  faWind,
  faWater,
  faWaterRise,
  faWaterLower,
  faFire,
  faHurricane,
  faRaindrops,
  faUmbrella,
  faSnowflake,
  faTemperatureLow,
  faTemperatureHigh,
  faUmbrellaBeach,

  // OTHER
  faBurgerSoda,
  faGlassCitrus,
  faUtensils,
  faFish,
  faTrophy,
  faTrophyAlt,
  faMedal,
  faMagic,
  faVirus,
  faEye,
  faEyeSlash,
  faThumbsDown,
  faThumbsUp,
  faHandPointRight,
  faHandPointLeft,
  faBan,
  faSort,
  faAt,
  faCreditCard,
  faHammer,
  faMoneyBillAlt,
  faUniversity,
  faDownload,
} from '@fortawesome/pro-regular-svg-icons';

library.add(
  faCcPaypal,
  faCcVisa,
  faCcMastercard,
  faCcDiscover,
  faCcApplePay,
  faCcAmex,
  faApplePay,
  faGooglePay,
  faCcJcb,
  faCcDinersClub,
  faFolderSolid,
  faFolderOpenSolid,
  faFileSolid,
  faFileAltSolid,
  faClipboardListSolid,
  faFilePdfSolid,
  faFileInvoiceSolid,
  faNewspaperSolid,
  faIdCardSolid,
  faCloneSolid,
  faPrintSolid,
  faLockSolid,
  faLockAltSolid,
  faBriefcaseSolid,
  faWindowMaximizeSolid,
  faColumnsSolid,
  faSquareFullSolid,
  faUploadSolid,
  faDatabaseSolid,
  faArchive,

  faCalendarAltSolid,
  faCalendarDaySolid,
  faCalendarCheckSolid,
  faCalendarTimesSolid,
  faClockSolid,
  faAlarmClockSolid,
  faHistorySolid,
  faRedoSolid,
  faSyncSolid,

  faFilterSolid,
  faListOlSolid,
  faListSolid,
  faBarsSolid,
  faEllipsisHSolid,
  faEllipsisVSolid,
  faEditSolid,
  faExternalLinkSolid,
  faTrashAltSolid,
  faSaveSolid,
  faCogSolid,
  faTachometerAltSolid,
  faPlusCircleSolid,
  faMinusCircleSolid,
  faStarSolid,
  faStarsSolid,
  faHeartSolid,
  faShipSolid,
  faCardSolid,

  faCheckSolid,
  faCheckDoubleSolid,
  faShieldCheckSolid,
  faCheckCircleSolid,
  faClipboardCheckSolid,
  faClipboardListCheckSolid,
  faSearchSolid,
  faTimesSolid,
  faCircleSolid,
  faQuestionCircleSolid,
  faInfoCircleSolid,
  faInfoSolid,
  faExclamationCircleSolid,

  faChevronUpSolid,
  faChevronDownSolid,
  faLongArrowAltUp,
  faChevronRightSolid,
  faChevronLeftSolid,
  faArrowRightSolid,
  faArrowLeftSolid,
  faSignOutSolid,
  faSignInSolid,
  faSortAltSolid,
  faExchangeAltSolid,
  faRandomSolid,
  faCaretDownSolid,

  faUserSolid,
  faUserCircleSolid,
  faUsersSolid,
  faUserFriendsSolid,
  faChildSolid,
  faWheelchairSolid,
  faSwimmerSolid,

  faMapSolid,
  faMapMarkerAltSolid,
  faThumbtackSolid,
  faMapMarkedAltSolid,
  faLocationArrowSolid,
  faGlobeAmericasSolid,
  faLocationSolid,
  faAnchorSolid,

  faCoinsSolid,
  faUsdCircleSolid,
  faHandHoldingUsdSolid,
  faDollarSignSolid,
  faMoneyBillWaveSolid,
  faPiggyBankSolid,
  faMoneyCheckAltSolid,
  faMoneyCheckSolid,

  faChartLineSolid,
  faChartBarSolid,
  faSignalSolid,
  faWaveformPathSolid,
  faWifiSolid,
  faWifiSlashSolid,
  faWrenchSolid,
  faCameraSolid,
  faImageSolid,
  faImagesSolid,
  faFilmSolid,
  faMobileAltSolid,
  faPlaySolid,
  faPauseSolid,

  faCommentSolid,
  faCommentsSolid,
  faCommentCheckSolid,
  faSmsSolid,
  faEnvelopeSolid,
  faPaperPlaneSolid,
  faLightbulbOnSolid,
  faBellSolid,
  faBellsSolid,
  faMegaphoneSolid,
  faPhoneAltSolid,
  faShareAltSolid,
  faInboxInSolid,
  faInboxOutSolid,

  faBoltSolid,
  faMoonSolid,
  faCloudsSolid,
  faWindSolid,
  faWaterSolid,
  faWaterRiseSolid,
  faWaterLowerSolid,
  faFireSolid,
  faHurricaneSolid,
  faRaindropsSolid,
  faUmbrellaSolid,
  faSnowflakeSolid,
  faTemperatureLowSolid,
  faTemperatureHighSolid,
  faUmbrellaBeachSolid,

  faBurgerSodaSolid,
  faGlassCitrusSolid,
  faUtensilsSolid,
  faFishSolid,
  faTrophySolid,
  faTrophyAltSolid,
  faMedalSolid,
  faMagicSolid,
  faVirusSolid,
  faEyeSolid,
  faEyeSlashSolid,
  faThumbsDownSolid,
  faThumbsUpSolid,
  faHandPointRightSolid,
  faHandPointLeftSolid,
  faBanSolid,
  faCreditCardSolid,

  faSortSolid,
  faMoneyBillAltSolid,
  faUniversitySolid,

  faFolder,
  faFolderOpen,
  faFile,
  faFileAlt,
  faClipboardList,
  faFilePdf,
  faFileInvoice,
  faNewspaper,
  faIdCard,
  faClone,
  faPrint,
  faLock,
  faBriefcase,
  faWindowMaximize,
  faColumns,
  faSquareFull,
  faUpload,
  faDatabase,

  faCalendarAlt,
  faCalendarDay,
  faCalendarCheck,
  faCalendarTimes,
  faClock,
  faAlarmClock,
  faHistory,
  faRedo,
  faSync,

  faFilter,
  faListOl,
  faList,
  faBars,
  faEllipsisH,
  faEllipsisV,
  faEdit,
  faExternalLink,
  faTrashAlt,
  faSave,
  faCog,
  faTachometerAlt,
  faPlusCircle,
  faMinusCircle,
  faStar,
  faStars,
  faHeart,
  faShip,
  faCar,

  faCheck,
  faCheckDouble,
  faShieldCheck,
  faCheckCircle,
  faClipboardCheck,
  faClipboardListCheck,
  faSearch,
  faTimes,
  faCircle,
  faQuestionCircle,
  faInfoCircle,
  faInfo,
  faExclamationCircle,

  faChevronUp,
  faChevronDown,
  faChevronRight,
  faChevronLeft,
  faArrowRight,
  faArrowLeft,
  faSignOut,
  faSignOutAlt,
  faSignOutAltSolid,
  faLevelUp,
  faLevelUpSolid,
  faArrowToBottom,
  faArrowToBottomSolid,
  faSignIn,
  faSortAlt,
  faExchangeAlt,
  faRandom,
  faCaretDown,
  faArrowCircleUpSolid,

  faUser,
  faUserCircle,
  faUsers,
  faUserFriends,
  faChild,
  faWheelchair,
  faSwimmer,

  faMap,
  faMapMarkerAlt,
  faThumbtack,
  faMapMarkedAlt,
  faLocationArrow,
  faGlobeAmericas,
  faLocation,
  faAnchor,

  faCoins,
  faUsdCircle,
  faHandHoldingUsd,
  faDollarSign,
  faMoneyBillWave,
  faPiggyBank,
  faMoneyCheckAlt,
  faMoneyCheck,

  faChartLine,
  faChartBar,
  faSignal,
  faWaveformPath,
  faWifi,
  faWifiSlash,
  faWrench,
  faCamera,
  faImage,
  faImages,
  faFilm,
  faMobileAlt,
  faPlay,
  faPause,
  faHeadset,

  faComment,
  faComments,
  faCommentCheck,
  faSms,
  faEnvelope,
  faPaperPlane,
  faLightbulbOn,
  faBell,
  faBells,
  faMegaphone,
  faPhoneAlt,
  faShareAlt,
  faInboxIn,
  faInboxOut,

  faBolt,
  faMoon,
  faClouds,
  faWind,
  faWater,
  faWaterRise,
  faWaterLower,
  faFire,
  faHurricane,
  faRaindrops,
  faUmbrella,
  faSnowflake,
  faTemperatureLow,
  faTemperatureHigh,
  faUmbrellaBeach,

  faBurgerSoda,
  faGlassCitrus,
  faUtensils,
  faFish,
  faTrophy,
  faTrophyAlt,
  faMedal,
  faMagic,
  faVirus,
  faEye,
  faEyeSlash,
  faThumbsDown,
  faThumbsUp,
  faHandPointRight,
  faHandPointLeft,
  faBan,
  faSort,
  faAngleRightSolid,
  faAngleDownSolid,
  faAt,
  faCreditCard,
  faHammer,
  faMoneyBillAlt,
  faUniversity,
  faUndoSolid,
  faDownload,
  faDownloadSolid,
);
